[package]
name = "tgbot"
description = "A Telegram Bot library"
version = "0.17.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/tgbot"
repository = "https://github.com/tg-rs/tgbot"

[dependencies]
async-stream = "0.3"
bytes = "1.1"
derive_more = "0.99"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["server"] }
log = "0.4"
mime = "0.3"
mime_guess = "2.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "socks", "rustls-tls", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellwords = "1.1"
tokio = { version = "1.16", features = ["fs", "sync", "time"] }
tokio-util = { version = "0.6", features = ["codec"] }
vec1 = { version = "1.8", features = ["serde"] }

[dev-dependencies]
dotenv = "0.15"
env_logger = "0.9"
mockito = "0.30"
regex = "1.5"
tempfile = "3.3"
tokio = {version = "1.16", features = ["fs", "io-util", "macros", "rt-multi-thread"]}
toml = "0.5"

[package.metadata.docs.rs]
all-features = true
